### ISSUE TITLE
Parsing classpath in manifest is wrong if multiple line

### ISSUE THREAD

**Issue by zero-88** [classgraph/classgraph#305]
Parsing wrong jar filename in classpath:
- `lib/demo-core-cluste` should be `lib/demo-core-cluster-hazelcast-1.0.0-SNAPSHOT.jar`

**More information:**
- Using default `gradle java plugin` to write manifest 
    ```
    manifest {
      attributes(['Class-Path': configurations.runtimeClasspath.files.collect { "lib/${it.getName()}"}.join(" ")])
    }
    ```

- Maybe error from here:
[LogicalZipFile.java#L260-L264](https://github.com/classgraph/classgraph/blob/master/src/main/java/nonapi/io/github/classgraph/fastzipfilereader/LogicalZipFile.java#L260-L264) or [LogicalZipFile.java#L125](https://github.com/classgraph/classgraph/blob/master/src/main/java/nonapi/io/github/classgraph/fastzipfilereader/LogicalZipFile.java#L125)

- From java docs
https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#Name-Value_pairs_and_Sections
    ```
    value:          SPACE *otherchar newline *continuation
    continuation:   SPACE *otherchar newline
    ```

**Debug log**
```
2019-01-29T16:55:50.934+0700	ClassGraph	ClassGraph version 4.6.2
2019-01-29T16:55:50.935+0700	ClassGraph	Operating system: Linux 4.15.0-43-generic amd64
2019-01-29T16:55:50.935+0700	ClassGraph	Java version: 1.8.0_201 / 1.8.0_201-b09 (Oracle Corporation)
2019-01-29T16:55:50.935+0700	ClassGraph	Java home: /home/jvm/java/8.0.201-oracle/jre
2019-01-29T16:55:50.935+0700	ClassGraph	JRE jars:
2019-01-29T16:55:50.935+0700	ClassGraph	-- /home/jvm/java/8.0.201-oracle/jre/lib/rt.jar
2019-01-29T16:55:50.938+0700	ClassGraph	ScanSpec:
2019-01-29T16:55:50.938+0700	ClassGraph	-- packageWhiteBlackList: whitelist: [com.pr.core.cluster]
2019-01-29T16:55:50.938+0700	ClassGraph	-- packagePrefixWhiteBlackList: whitelistPrefixes: [com.pr.core.cluster.]
2019-01-29T16:55:50.938+0700	ClassGraph	-- pathWhiteBlackList: whitelist: [com/pr/core/cluster/]
2019-01-29T16:55:50.938+0700	ClassGraph	-- pathPrefixWhiteBlackList: whitelistPrefixes: [com/pr/core/cluster/]
2019-01-29T16:55:50.938+0700	ClassGraph	-- classWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- classfilePathWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- classPackageWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- classPackagePathWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- moduleWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- jarWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- classpathElementResourcePathWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- libOrExtJarWhiteBlackList: 
2019-01-29T16:55:50.938+0700	ClassGraph	-- performScan: true
2019-01-29T16:55:50.938+0700	ClassGraph	-- scanJars: true
2019-01-29T16:55:50.938+0700	ClassGraph	-- scanNestedJars: true
2019-01-29T16:55:50.938+0700	ClassGraph	-- scanDirs: true
2019-01-29T16:55:50.939+0700	ClassGraph	-- scanModules: true
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableClassInfo: true
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableFieldInfo: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableMethodInfo: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableAnnotationInfo: true
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableStaticFinalFieldConstantInitializerValues: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableExternalClasses: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- enableSystemJarsAndModules: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- ignoreClassVisibility: true
2019-01-29T16:55:50.939+0700	ClassGraph	-- ignoreFieldVisibility: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- ignoreMethodVisibility: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- disableRuntimeInvisibleAnnotations: false
2019-01-29T16:55:50.939+0700	ClassGraph	-- extendScanningUpwardsToExternalClasses: true
2019-01-29T16:55:50.940+0700	ClassGraph	-- addedClassLoaders: null
2019-01-29T16:55:50.940+0700	ClassGraph	-- overrideClassLoaders: null
2019-01-29T16:55:50.940+0700	ClassGraph	-- addedModuleLayers: null
2019-01-29T16:55:50.940+0700	ClassGraph	-- overrideModuleLayers: null
2019-01-29T16:55:50.940+0700	ClassGraph	-- overrideClasspath: null
2019-01-29T16:55:50.940+0700	ClassGraph	-- classpathElementFilters: null
2019-01-29T16:55:50.940+0700	ClassGraph	-- initializeLoadedClasses: false
2019-01-29T16:55:50.940+0700	ClassGraph	-- removeTemporaryFilesAfterScan: false
2019-01-29T16:55:50.940+0700	ClassGraph	-- ignoreParentClassLoaders: false
2019-01-29T16:55:50.940+0700	ClassGraph	-- ignoreParentModuleLayers: false
2019-01-29T16:55:50.941+0700	ClassGraph	Finding classpath entries
2019-01-29T16:55:50.946+0700	ClassGraph	-- Finding classpath and modules
2019-01-29T16:55:50.946+0700	ClassGraph	---- System jars:
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for rt.jar: /home/jvm/java/8.0.201-oracle/jre/lib/rt.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/jconsole.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/ant-javafx.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/dt.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/javafx-mx.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/packager.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/tools.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/lib/sa-jdi.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/jce.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/jsse.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/charsets.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/deploy.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/management-agent.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/plugin.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/javaws.jar
2019-01-29T16:55:50.946+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/jfr.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/jfxswt.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/resources.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/jaccess.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/sunjce_provider.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/nashorn.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/jfxrt.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/cldrdata.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/sunec.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/sunpkcs11.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/zipfs.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/localedata.jar
2019-01-29T16:55:50.947+0700	ClassGraph	------ Scanning disabled for lib or ext jar: /home/jvm/java/8.0.201-oracle/jre/lib/ext/dnsns.jar
2019-01-29T16:55:50.950+0700	ClassGraph	---- Found ClassLoaders:
2019-01-29T16:55:50.950+0700	ClassGraph	------ sun.misc.Launcher$AppClassLoader@74a14482
2019-01-29T16:55:50.950+0700	ClassGraph	---- Found system modules:
2019-01-29T16:55:50.950+0700	ClassGraph	------ [None]
2019-01-29T16:55:50.953+0700	ClassGraph	---- Found non-system modules:
2019-01-29T16:55:50.953+0700	ClassGraph	------ [None]
2019-01-29T16:55:50.953+0700	ClassGraph	---- ClassLoaderHandlers:
2019-01-29T16:55:50.957+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.AntClassLoaderHandler
2019-01-29T16:55:50.957+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.EquinoxClassLoaderHandler
2019-01-29T16:55:50.957+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.EquinoxContextFinderClassLoaderHandler
2019-01-29T16:55:50.957+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.FelixClassLoaderHandler
2019-01-29T16:55:50.957+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.JBossClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.WeblogicClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.WebsphereLibertyClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.WebsphereTraditionalClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.OSGiDefaultClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.SpringBootRestartClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.ParentLastDelegationOrderTestClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.JPMSClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	------ nonapi.io.github.classgraph.classloaderhandler.URLClassLoaderHandler
2019-01-29T16:55:50.958+0700	ClassGraph	---- ClassLoader sun.misc.Launcher$AppClassLoader@74a14482 will be handled by nonapi.io.github.classgraph.classloaderhandler.URLClassLoaderHandler@f67be32
2019-01-29T16:55:50.958+0700	ClassGraph	---- sun.misc.Launcher$AppClassLoader@74a14482 delegates to parent sun.misc.Launcher$ExtClassLoader@6a2b953e with order PARENT_FIRST
2019-01-29T16:55:50.958+0700	ClassGraph	---- ClassLoader sun.misc.Launcher$ExtClassLoader@6a2b953e will be handled by nonapi.io.github.classgraph.classloaderhandler.URLClassLoaderHandler@330e6602
2019-01-29T16:55:50.958+0700	ClassGraph	---- Finding classpath elements in ClassLoaders
2019-01-29T16:55:50.959+0700	ClassGraph	---- Finding classpath elements in ClassLoader sun.misc.Launcher$ExtClassLoader@6a2b953e
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/jaccess.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/jaccess.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/sunjce_provider.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/sunjce_provider.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/nashorn.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/nashorn.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/jfxrt.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/jfxrt.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/cldrdata.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/cldrdata.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/sunec.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/sunec.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/sunpkcs11.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/sunpkcs11.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/zipfs.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/zipfs.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/localedata.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/localedata.jar
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: file:/home/jvm/java/8.0.201-oracle/jre/lib/ext/dnsns.jar -> /home/jvm/java/8.0.201-oracle/jre/lib/ext/dnsns.jar
2019-01-29T16:55:50.959+0700	ClassGraph	---- Finding classpath elements in ClassLoader sun.misc.Launcher$AppClassLoader@74a14482
2019-01-29T16:55:50.959+0700	ClassGraph	------ Found classpath element: file:/home/javaproject/demo/tmp/demo-comp-1.0.0-SNAPSHOT.jar -> /home/javaproject/demo/tmp/demo-comp-1.0.0-SNAPSHOT.jar
2019-01-29T16:55:50.959+0700	ClassGraph	---- Getting classpath entries from java.class.path
2019-01-29T16:55:50.959+0700	ClassGraph	------ Ignoring duplicate classpath element: demo-comp-1.0.0-SNAPSHOT.jar -> /home/javaproject/demo/tmp/demo-comp-1.0.0-SNAPSHOT.jar
2019-01-29T16:55:50.959+0700	ClassGraph	-- Reading jarfile directories and manifest files (took 0.018728 sec)
2019-01-29T16:55:50.966+0700	ClassGraph	---- Opening jarfile /home/javaproject/demo/tmp/demo-comp-1.0.0-SNAPSHOT.jar
2019-01-29T16:55:50.969+0700	ClassGraph	------ Found Class-Path entry in manifest file: lib/demo-core-1.0.0-SNAPSHOT.jar lib/demo-core-cluste
2019-01-29T16:55:50.969+0700	ClassGraph	---- Opening jarfile /home/javaproject/demo/tmp/lib/demo-core-1.0.0-SNAPSHOT.jar
2019-01-29T16:55:50.970+0700	ClassGraph	-- Skipping classpath element /home/javaproject/demo/tmp/lib/demo-core-cluste : java.io.FileNotFoundException: File/directory not found
2019-01-29T16:55:50.972+0700	ClassGraph	-- Final classpath element order:
2019-01-29T16:55:50.972+0700	ClassGraph	---- /home/javaproject/demo/tmp/demo-comp-1.0.0-SNAPSHOT.jar
2019-01-29T16:55:50.972+0700	ClassGraph	---- /home/javaproject/demo/tmp/lib/demo-core-1.0.0-SNAPSHOT.jar
2019-01-29T16:55:50.972+0700	ClassGraph	-- Scanning filenames within classpath elements
2019-01-29T16:55:50.972+0700	ClassGraph	---- Scanning jarfile classpath element /home/javaproject/demo/tmp/lib/demo-core-1.0.0-SNAPSHOT.jar (took 0.000760 sec)
2019-01-29T16:55:50.972+0700	ClassGraph	---- Scanning jarfile classpath element /home/javaproject/demo/tmp/demo-comp-1.0.0-SNAPSHOT.jar (took 0.000676 sec)
2019-01-29T16:55:50.978+0700	ClassGraph	Masking classfiles
2019-01-29T16:55:50.978+0700	ClassGraph	Scanning classfiles (took 0.000695 sec)
2019-01-29T16:55:50.979+0700	ClassGraph	Building class graph (took 0.000099 sec)
2019-01-29T16:55:50.982+0700	ClassGraph	Completed (took 0.036589 sec)
```

**MANIFEST.mf**
Line break: `LF`
```
Class-Path: lib/demo-edge-core-1.0.0-SNAPSHOT.jar lib/demo-core-cluste
 r-hazelcast-1.0.0-SNAPSHOT.jar lib/demo-core-sql-1.0.0-SNAPSHOT.jar l
 ib/demo-eventbus-edge-1.0.0-SNAPSHOT.jar lib/demo-ext-rx-jdbc-1.0.0-S
 NAPSHOT.jar lib/demo-core-base-1.0.0-SNAPSHOT.jar lib/vertx-maven-ser
 vice-factory-3.6.0.jar lib/vertx-hazelcast-3.6.0.jar lib/vertx-jooq-r
 x-4.0.0.jar lib/vertx-rx-java2-3.6.0.jar lib/vertx-config-3.6.0.jar l
 ib/vertx-service-factory-3.6.0.jar lib/vertx-rx-java2-gen-3.6.0.jar l
 ib/vertx-jdbc-client-3.6.0.jar lib/vertx-sql-common-3.6.0.jar lib/ver
 tx-rx-gen-3.6.0.jar lib/vertx-jooq-shared-4.0.0.jar lib/vertx-core-3.
 6.0.jar lib/vertx-codegen-3.6.0.jar lib/jackson-databind-2.9.8.jar li
 b/jackson-core-2.9.8.jar lib/logback-classic-1.2.3.jar lib/HikariCP-3
 .2.0.jar lib/slf4j-api-1.7.25.jar lib/netty-codec-http2-4.1.30.Final.
 jar lib/netty-handler-4.1.30.Final.jar lib/netty-handler-proxy-4.1.30
 .Final.jar lib/netty-resolver-dns-4.1.30.Final.jar lib/netty-codec-ht
 tp-4.1.30.Final.jar lib/netty-codec-socks-4.1.30.Final.jar lib/netty-
 codec-dns-4.1.30.Final.jar lib/netty-codec-4.1.30.Final.jar lib/netty
 -transport-4.1.30.Final.jar lib/netty-buffer-4.1.30.Final.jar lib/net
 ty-resolver-4.1.30.Final.jar lib/netty-common-4.1.30.Final.jar lib/ja
 ckson-annotations-2.9.0.jar lib/logback-core-1.2.3.jar lib/h2-1.4.197
 .jar lib/hazelcast-3.10.6.jar lib/classgraph-4.6.2.jar lib/javax.pers
 istence-api-2.2.jar lib/jooq-meta-3.11.8.jar lib/jooq-3.11.8.jar lib/
 maven-aether-provider-3.1.0.jar lib/aether-connector-basic-1.1.0.jar 
 lib/aether-transport-file-1.1.0.jar lib/aether-transport-http-1.1.0.j
 ar lib/aether-impl-1.1.0.jar lib/aether-spi-1.1.0.jar lib/aether-util
 -1.1.0.jar lib/aether-api-1.1.0.jar lib/httpclient-4.5.3.jar lib/comm
 ons-logging-1.2.jar lib/jaxb-api-2.2.12.jar lib/maven-model-builder-3
 .1.0.jar lib/maven-model-3.1.0.jar lib/maven-repository-metadata-3.1.
 0.jar lib/plexus-utils-3.0.10.jar lib/httpcore-4.4.6.jar lib/commons-
 codec-1.9.jar lib/rxjava-2.2.4.jar lib/reactive-streams-1.0.2.jar lib
 /plexus-interpolation-1.16.jar lib/mvel2-2.3.1.Final.jar conf/*
```

**Comment by lukehutch** [comment]
@zero-88 Thanks for the report. I just pushed out a fix for this a couple of hours ago, release 4.6.22. You are using an old version, 4.6.2. Can you please update to 4.6.22 and test if this solves the issue?

**Comment by zero-88** [comment]
Still happens, man.
I think this issue due to parsing manifest value

**Comment by lukehutch** [comment]
@zero-88 Sorry, I fixed one buy in 4.6.22 and introduced another one. Please try 4.6.23, this should be fixed now.

**Comment by zero-88** [comment]
Awesome, it fixed. You're so very fast as your lib. 
Great work, thank man

Note: I just tested in local clone repository, not yet downloaded from public repository

**Comment by lukehutch** [comment]
@zero-88 You're welcome! I try to respond fast, always, because almost no open source project I have ever reported bugs to has been very responsive!

Yes, unfortunately it can take a couple of hours for Maven Central to sync and publish the artifacts after I push out a release.

Thanks for the bug report!
