### ISSUE TITLE
ScanResult.getModulePath()

### ISSUE THREAD

**Issue by cowwoc** [classgraph/classgraph#308]
`ScanResult.getClassPath()` results the application classpath. Shouldn't there be a corresponding `ScanResult.getModulePath()` method?

**Comment by lukehutch** [comment]
@cowwoc Yes, there is `ScanResult.getModules()` -- is this what you need?

**Comment by cowwoc** [comment]
Yes and no. `ScanResult.getClassPath()` returns the `String` representation of `getClasspathFiles()`. In the same way, I was expecting `ScanResult.getModulePath()` to return the `String` representation of `getModules()`. Essentially I am expecting to get back the same thing that was passed into the command-line.

I am using this for debugging (figuring out why a module can't be found, double-checking that it's there).

On a side-note: awesome library!

**Comment by lukehutch** [comment]
Thanks! Glad you find it useful.

You can get the name or location URL of each of the returned modules, and concatenate them... But I don't think there's a way to determine what was passed to the JRE on the commandline. By the time user code is running, all the module resolution has already taken place, and the modules are already arranged into a DAG of ModuleLayers. Maybe one of the ModuleLayers is specifically reserved for modules passed on the commandline? If you find something like that, or if you find a way to get the raw commandline passed to the JRE (maybe from an environment variable?), we can add that to ClassGraph. But it's not super straightforward to provide a module path, because internally it's a DAG, not a path, and on the commandline modules can be overridden, blacklisted, etc. (not just added).

**Comment by lukehutch** [comment]
For now it looks like this will work for you:

```
List<String> arguments = ManagementFactory.getRuntimeMXBean().getInputArguments();
```

Do you think it's worth it to parse these arguments and return them via the ClassGraph API?

**Comment by lukehutch** [comment]
@cowwoc Please try the git master version -- I added a new class that should have the info you need:

https://github.com/classgraph/classgraph/blob/master/src/main/java/io/github/classgraph/ModulePathInfo.java

There are two new methods that return a `ModulePathInfo`:

* `ClassGraph#getModulePathInfo()`, which returns only the module path info specified on the commandline
* `ScanResult#getModulePathInfo()`, which returns the module path info from the commandline, and additionally any `Add-Exports` and `Add-Opens` entries found in manifest files during a scan.

**Comment by lukehutch** [comment]
I'm pretty sure this is what you were looking for, so I released it as 4.6.32. Let me know if there are any issues, and I can re-open the bug. Thanks for the feature request!

**Comment by cowwoc** [comment]
Thank you for the quick turnaround but this still isn't exactly what I was looking for in the sense that I was looking for an order-preserving `String`. That said, maybe all I really want is to invoke `ManagementFactory.getRuntimeMXBean().getInputArguments()`. I'm guessing you don't really want to expose a `getCommandLine()` option in your API that does this (it isn't really a perfect fit for what you do) so the functionality you've added should be fine.

One thing to watch out for is using `Set` to captuer the module path. It is perfectly legal for users to pass in multiple entries that have the same module name (in which case a "module shadowing" of sorts happens, similar to classpath shadowing). I'm not sure if the same applies for addModules, patchModules and others but it's worth checking. Using ` List` and preserving duplicates should be sufficient.

**Comment by lukehutch** [comment]
You can just call this yourself, yes -- it doesn't make sense to wrap that one function call, no. The reason I wrote the `ModulePathInfo` class was (1) to save you from parsing the returned string, and (2) (this was the kicker) because I discovered that manifest files can contain `Add-Exports` and `Add-Opens` entries, similar to how the manifest can contain `Class-Path` entries to extend the classpath (so if you just call the management bean yourself, you will not get those entries).

Note that the sets used in that class are `LinkedHashSet`, which are order-preserving (intentionally so). If you call `ModulePathInfo#toString()` you'll get the command line arguments in the same *relative* order as on the commandine, albeit with duplicates removed, and with arguments grouped together by switch type (in the order specified in `toString()`). So semantically, it is probably still what you want, and it is additionally cleaned up a bit.

**Comment by lukehutch** [comment]
I'm pretty sure that module shadowing should have no effect if the same module is passed in twice, since they are processed in order, so only the first instance will do anything. (If not, please give an example of how the second and subsequent usage can change the semantics, and I will change the API before anyone starts using it!)

**Comment by cowwoc** [comment]
Sounds correct to me. Thanks for the clarification.
