### ISSUE TITLE
When using wildfly 21, the jar under WEB-INF/lib will not be displayed.

### ISSUE THREAD

**Issue by LanlingCL** [classgraph/classgraph#701]
Hello, I have a project deployed with wildfly21. I upgraded classgraph from 4.8.129 to 4.8.149 and put a test jar in the same directory as ant-1.10.11.jar in WEB-INF/lib.

It is found that classgraph will no longer display the jars under WEB-INF/lib, leaving only the jar packages under standalone/tmp/vfs/deployment, which is not an expected result.

```java
for (Entry<String, ResourceList> dup :
        new ClassGraph().verbose().scan()
            .getAllResources()
            .classFilesOnly()
            .findDuplicatePaths()) {
    System.out.println(dup.getKey());
    for (Resource res : dup.getValue()) {
        System.out.println(" -> " + res.getURI());
    }
}
```

Here is the output under version 4.8.129, which has jars in both WEB-INF/lib and standalone/tmp/vfs/deployment directories.(The standalone/tmp/vfs/deployment directory will be generated when wildfly starts, and the duplicate classes in this directory are not what I need. I will remove it manually in later code.)

```log
2022-08-11 15:55:30,651 INFO [stdout] (default task-1) org/apache/tools/ant/AntClassLoader.class
2022-08-11 15:55:30,651 INFO [stdout] (default task-1) -> jar:file:/E:/wildfly-21.0.2.Final/standalone/deployments/project.ear/project.war/WEB-INF/lib/ant-test.jar!/org/apache/tools/ant/AntClassLoader.class 
2022-08-11 15:55:30,651 INFO [stdout] (default task-1) -> jar:file:/E:/wildfly-21.0.2.Final/standalone/deployments/project.ear/project.war/WEB-INF/lib/ant-1.10.11.jar!/org/apache/tools/ant/AntClassLoader.class 
2022-08-11 15:55:30,651 INFO [stdout] (default task-1) -> jar:file:/E:/wildfly-21.0.2.Final/standalone/tmp/vfs/deployment/deployment3c10fbd71b13340a/ant-1.10.11.jar-3a7bfe1548c3a3e/ant-1.10.11.jar!/org/apache/tools/ant/AntClassLoader.class 
2022-08-11 15:55:30,652 INFO [stdout] (default task-1) -> jar:file:/E:/wildfly-21.0.2.Final/standalone/tmp/vfs/deployment/deployment3c10fbd71b13340a/ant-test.jar-55a4bb8fdf420ca2/ant-test.jar!/org/apache/tools/ant/AntClassLoader.class 
```

This is the output under version 4.8.149, it only has the jars under standalone/tmp/vfs/deployment.

```log
2022-08-11 15:40:48,028 INFO [stdout] (default task-1) org/apache/tools/ant/AntClassLoader.class
2022-08-11 15:40:48,028 INFO [stdout] (default task-1) -> jar:file:/E:/wildfly-21.0.2.Final/standalone/tmp/vfs/deployment/deployment190ae1711ba8c466/ant-1.10.11.jar-edacd854758a48eb/ant-1.10.11.jar!/org/apache/tools/ant/AntClassLoader.class 
2022-08-11 15:40:48,028 INFO [stdout] (default task-1) -> jar:file:/E:/wildfly-21.0.2.Final/standalone/tmp/vfs/deployment/deployment190ae1711ba8c466/ant-test.jar-be18d95f67ae544c/ant-test.jar!/org/apache/tools/ant/AntClassLoader.class
```

My project needs to display duplicate classes in jar under WEB-INF/lib.

Is this an issue? If not, is there any way to display the duplicate classes in the WEB-INF/lib directory?

P.S. I called  `ClassGraph#verbose()`, but the project outputs 20,000 classgraph logs, so if there is a need, tell me the part you need, and I will intercept it and upload it.

**Comment by lukehutch** [comment]
@LanlingCL I'm sorry it took me so long to get to this bug.

I definitely will need the verbose logs to see what is going on. The main thing to look for is the part near the top where the classpath elements are found for each classloader (is `WEB-INF/lib` found?), and then if it is found but not scanned, look to see if there are any warnings about classpath elements being skipped for some reason.

**Comment by lukehutch** [comment]
@LanlingCL Any chance you can attach full logs to this bug report, please?

**Comment by mainsys-bme** [comment]
Hello @lukehutch 
We noticed this issue cause the webjar-locator to stop working with latest Jboss EAP 7.4.15 update which remove the content of vfs jar folder to avoir duplicating .jar on the disk. (see https://issues.redhat.com/browse/JBEAP-25881 and https://issues.redhat.com/browse/JBEAP-25677 from 7.4 update 15 patch note).

I have successfully make webjar-locator work again by setting manually version 4.8.129 of ClassGraph in my pom.xml dependencies to validate this was the cause of the issue.
I will try to find the exact version at which the issue start.
**edit: From my test it occurs between 4.8.143 and 4.8.144**

I will also see if I can provide logs but I will maybe have to build a sample project for that so I can guarantee anything.

**Comment by lukehutch** [comment]
Thanks for following up on this. I can't do anything without log info, but if you can't provide the full logs, at least please provide the part at the top (for both the broken and working case) that shows which classloaders were found, and which classpath elements were found in each classloader.

**Comment by mainsys-bme** [comment]
[log.zip](https://github.com/classgraph/classgraph/files/14310491/log.zip)
Hello, 
I create a sandbox project where I removed most of unecessary dependencies to do the test and kept only my webjars and and the base structure.
It produce the two attached log files one in 4.8.143 which find the ~4k resources in my webjars and one in 4.8.144 which find none of them.
My sandbox app is a single spring configuration class where I only perform the scan and log the number of resources I found (i did it in a bean as WebjarsResourceResolver is called during bean initialization/injection phase and it is when the scan occurs in our app.
```
@Configuration
public class SpringBeans {

    @Bean(name="webjarList")
    public ResourceList webjarResource()
    {
        ResourceList resources = new ClassGraph().verbose().acceptPaths("META-INF/resources/webjars").scan().getAllResources();
        System.out.println(resources.size() + " resources found");
        return resources;
    }

}
```

**Comment by lukehutch** [comment]
Are these the jars you are missing?

```console
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/attoparser-2.0.7.RELEASE.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/bootstrap-5.3.2.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/bootstrap-datepicker-1.10.0.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/bootstrap-icons-1.11.2.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/classgraph-4.8.143.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/commons-lang3-3.13.0.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/commons-text-1.11.0.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/compiler-0.9.10.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/font-awesome-6.4.0.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jackson-annotations-2.14.3.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jackson-core-2.15.2.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jackson-databind-2.14.3.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/javassist-3.29.0-GA.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jquery-3.7.1.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jquery-i18n-properties-1.10.2.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jquery-ui-1.13.2.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/jquery-validation-1.19.5.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/ognl-3.3.4.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/slf4j-api-2.0.7.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-aop-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-beans-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-context-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-context-support-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-core-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-expression-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-jcl-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-web-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/spring-webmvc-5.3.31.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/thymeleaf-3.1.2.RELEASE.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/thymeleaf-spring5-3.1.2.RELEASE.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/tooltipster-4.2.8.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/unbescape-1.1.6.RELEASE.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/webjars-locator-0.50.jar
2024-02-16T11:17:09.427+0100	ClassGraph	-- C:/v/classgraph_test/classgraph_test/target/sandbox-webapp-1.0.0/WEB-INF/lib/webjars-locator-core-0.55.jar
```

If so, then yes, it appears that the auto-detection of `lib/` inside of `WEB-INF/` got broken in version 4.8.144.

I have to auto-detect the `lib/` directory, because the classloader doesn't actually return the lib jars in this directory in the classpath. There is code for this, and it is supposed to work, so I'll fix this, but I will need a test project to run, because I don't know anything about WildFly.

Can you please share your sandbox app, and full instructions for running it with version 4.8.143 and 4.8.144?

**Comment by mainsys-bme** [comment]
Hello 
Yes this are the .jar missing.
I have reproduce on wildfly 26.1.1.Final
https://github.com/wildfly/wildfly/releases/download/26.1.1.Final/wildfly-26.1.1.Final.zip
With maven 3.6.3 or 3.8.1
And Correto 8 402 as JDK
I attached my sandbox project with step to reproduce in command line, with inteliJ and some hints how to debug with other IDE. I also put some log sample with various configuration in the project.
[sandbox.zip](https://github.com/classgraph/classgraph/files/14329984/sandbox.zip)

Thank you for your reactivity

**Comment by lukehutch** [comment]
Hi,

I followed your steps (thanks for providing detailed instructions!).

At the deploy step, I get the error:

```console
luke@fedora:/tmp/x/sandbox$ 14:11:16,232 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0027: Starting deployment of "sandbox-webapp-1.0.0.war" (runtime-name: "sandbox-webapp-1.0.0.war")
14:11:16,691 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "sandbox-webapp-1.0.0.war" was rolled back with the following failure message: undefined
14:11:16,701 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0028: Stopped deployment sandbox-webapp-1.0.0.war (runtime-name: sandbox-webapp-1.0.0.war) in 9ms
14:11:16,701 INFO  [org.jboss.as.controller] (management-handler-thread - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildfly.undertow.listener.default: Address already in use /127.0.0.1:8080
```

However nothing is listening on port 8080:

```console
$ sudo ss -lptn 'sport = :8080'
State   Recv-Q   Send-Q     Local Address:Port     Peer Address:Port  Process   
$
```

**Comment by mainsys-bme** [comment]
Hello, 
I only get this error if I try to start twice the jboss by mistake or have another app listening on the port. 
If you use debug, make sure you don't start the debug feature on the same port.

Normally Jboss should be listening on 8080 even before deployment but as it is not a blocking error for starting, it fails only when the webapp attempt to start.

If you can't find what is using the 8080 there is the option to add -Djboss.socket.binding.port-offset=100 (or any other suitable offset) this will move jboss listening on http 8080 + offset instead. 
edit : I attempted to get rid of the servlet requirement but I realize it seems not trivial (if possible) and would alter deployment method.

**Comment by lukehutch** [comment]
I killed and restarted it a few times, without changing anything, and now it finally deploys... weird...

I can't figure out how to attach the Eclipse debugger to the running webapp, however. Do you have any suggestions?

**Comment by mainsys-bme** [comment]
I don't personally use Eclipse but it should look like in this guide : 
https://dzone.com/articles/how-debug-remote-java-applicat

If I have time to start an eclipse instance I will update with information.

**Comment by lukehutch** [comment]
The next 2 weeks are going to be extremely busy for me, so I'll have to return to this after that time. However, let me point you to the code that should be including this `lib/` directory. If you can trace through this in the debugger, please, and figure out why that directory is not being detected, I would appreciate it.

This is where `WEB-INF/lib` comes from:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/nonapi/io/github/classgraph/classloaderhandler/ClassLoaderHandlerRegistry.java#L92

Since this is in an unpacked jar, this is picked up here:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/io/github/classgraph/ClasspathElementDir.java#L109

However, this dir should also be able to be detected in jars, here:

https://github.com/classgraph/classgraph/blob/latest/src/main/java/io/github/classgraph/ClasspathElementZip.java#L211

If you set a breakpoint on these lines, or add some print statements, you will hopefully be able to see why in this particular case the `WEB-INF/lib` dir is not being picked up.

Thanks!

**Comment by mainsys-bme** [comment]
Thank you for those information.

For now we have settled to rely on the 4.8.143 for temporary solution.
As soon as I have time I will try to trace the issue based on your input.

**Comment by mmusenbr** [comment]
@lukehutch I think the issue is in https://github.com/classgraph/classgraph/blob/27fb1feac340a07f8e9393f2e96932ad886a038a/src/main/java/io/github/classgraph/ClasspathElementDir.java#L115
```java
if (Files.isRegularFile(filePath) && filePath.getFileName().endsWith(".jar")) {
```

There seems to be a misconception about `Path#endsWith`. this matches only if the last full path segment is. ('foo/bar' is matched by 'bar', but not by 'r'). And therefore all jars are skipped inside AUTOMATIC_LIB_DIR_PREFIXES sub-dirs.

Change the line to
```java
if (Files.isRegularFile(filePath) && filePath.toString().toLowerCase().endsWith(".jar")) {
```
should fix the detection.

**Comment by mmusenbr** [comment]
Opened a PR #834

**Comment by lukehutch** [comment]
Fixed in classgraph-4.8.168. Thank you for the report and the PR!

**Comment by mainsys-bme** [comment]
Thank you @mmusenbr and @lukehutch 
I didn't had time to investigate past weeks but I could do a quick test to confirm issue is still in 4.8.167 and not in 4.8.168 anymore
I will notify contributors of webjars-locator so they can bump the dependency version.

**Comment by lukehutch** [comment]
@mainsys-bme thanks for confirming!
